package com.apwglobal.nice.domain;

import java.util.Arrays;
import java.util.Collections;
import java.util.Map;
import java.util.stream.Collectors;

public enum Shipment {

    PACZKA_POCZTOWA_EKONOMICZNA(1),
    LIST_EKONOMICZNY(2),
    PACZKA_POCZTOWA_PRIORYTETOWA(3),
    LIST_PRIORYTETOWY(4),
    PRZESYLKA_POBRANIOWA_PACZKA48_POBRANIE(5),
    LIST_POLECONY_EKONOMICZNY(6),
    PRZESYLKA_POBRANIOWA_PRIORYTETOWA_PACZKA24_POBRANIE(7),
    LIST_POLECONY_PRIORYTETOWY(8),
    PRZESYLKA_KURIERSKA(9),
    ODBIOR_OSOBISTY(10),
    PRZESYLKA_KURIERSKA_POBRANIOWA(11),
    ODBIOR_W_PUNKCIE_PO_PRZEDPLACIE_PACZKA24_ODBIOR_W_PUNKCIE(10060),
    PRZESYLKA_ELEKTRONICZNA_EMAIL(12),
    ODBIOR_W_PUNKCIE_PO_PRZEDPLACIE_EPRZESYLKA_PACZKA48_ODBIOR_W_PUNKCIE(10061),
    ODBIOR_OSOBISTY_PO_PRZEDPLACIE(13),
    ALLEGRO_POLECONY_INPOST(16),
    POCZTEX_KURIER48(21),
    ODBIOR_W_PUNKCIE_PO_PRZEDPLACIE_PACZKA_W_RUCHU(10006),
    POCZTEX_KURIER48_POBRANIOWY(22),
    ODBIOR_W_PUNKCIE_PACZKA24_ODBIOR_W_PUNKCIE(20060),
    ODBIOR_W_PUNKCIE_EPRZESYLKA_PACZKA48_ODBIOR_W_PUNKCIE(20061),
    PACZKA24(30),
    PACZKA48(31),
    ODBIOR_W_PUNKCIE_PACZKA_W_RUCHU(20006),
    ODBIOR_W_PUNKCIE_PO_PRZEDPLACIE_PACZKOMATY_24_7(10022),
    ODBIOR_W_PUNKCIE_PO_PRZEDPLACIE_ALLEGRO_PACZKOMATY_INPOST(10023),
    ODBIOR_W_PUNKCIE_PACZKOMATY_24_7(20022),
    ODBIOR_W_PUNKCIE_ALLEGRO_PACZKOMATY_INPOST(20023);

    private int type;
    Shipment(int type) {
        this.type = type;
    }

    public static final Map<Integer, Shipment> VALUES;
    static {
        VALUES = Collections.unmodifiableMap(
                Arrays.stream(Shipment.values())
                        .collect(Collectors.toMap((Shipment v) -> v.type, v -> v))
        );
    }
}
